tickerBell/tickerBell-back

.github/workflows/deploy.yml
appspec.yml
build.gradle
scripts/gh_deploy.sh
src/main/resources/application-connection.yml

ci/cd 통합 테스트

---

src/test/java/com/tickerBell/TickerBellApplicationTests.java

fixed: 기본 테스트 코드 주석 후 cicd 재시도

fixed: 기본 테스트 코드 주석 후 cicd 재시도

---

.github/workflows/deploy.yml
build.gradle
src/main/java/com/tickerBell/security/SecurityConfig.java
src/main/java/com/tickerBell/test/TestController.java

미사용중인 h2 로직 제거 후 ci cd test

---

build.gradle
src/main/java/com/tickerBell/TickerBellApplication.java
src/main/java/com/tickerBell/domain/BaseEntity.java
src/main/java/com/tickerBell/domain/member/entity/AuthProvider.java
src/main/java/com/tickerBell/domain/member/entity/Member.java
src/main/java/com/tickerBell/domain/member/entity/Role.java
src/main/java/com/tickerBell/domain/member/repository/MemberRepository.java
src/main/java/com/tickerBell/global/config/P6SpySqlFormatter.java
src/main/java/com/tickerBell/global/config/SwaggerConfig.java
src/main/java/com/tickerBell/global/security/SecurityConfig.java
src/main/java/com/tickerBell/global/test/TestController.java
src/main/java/com/tickerBell/global/test/TestDto.java
src/test/java/com/tickerBell/domain/member/repository/MemberRepositoryTest.java
src/test/resources/application.yml

회원, 회원 리포지토리 클래스 생성, 회원 리포지토리 테스트 클래스 생성, 테스트를 위한 in memory 방식 h2 설정 yml 파일 생성

회원, 회원 리포지토리 생성

---

build.gradle
src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/dtos/JoinMemberRequest.java
src/main/java/com/tickerBell/domain/member/entity/Member.java
src/main/java/com/tickerBell/domain/member/repository/MemberRepository.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/global/security/config/SecurityConfig.java
src/main/java/com/tickerBell/global/security/context/MemberContext.java
src/main/java/com/tickerBell/global/security/dtos/LoginDto.java
src/main/java/com/tickerBell/global/security/dtos/LoginSuccessDto.java
src/main/java/com/tickerBell/global/security/filter/JwtAuthenticationFilter.java
src/main/java/com/tickerBell/global/security/service/CustomUserDetailsService.java
src/main/java/com/tickerBell/global/security/token/JwtTokenProvider.java
src/main/resources/application-app.yml
src/test/java/com/tickerBell/domain/member/repository/MemberRepositoryTest.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java

회원가입 이후 필터를 이용해 /api/login 으로 요청이 들어오면 id, password 검증 후 간단하게 accessToken과 refreshToken 을 넘기는 것으로 개발하였으며 향후 지속적으로 리팩터링 예정입니다.

회원가입 / 로그인 성공 시 간단하게 token 을 넘기는 것으로 개발하였습니다.

---

src/test/java/com/tickerBell/domain/member/controller/MemberApiControllerTest.java
src/test/java/com/tickerBell/domain/member/repository/MemberRepositoryTest.java
src/test/resources/application.yml

테스트를 위한 yml 파일 변경 및 회원가입 테스트 작성

MemberApiController 테스트 작성

---

src/test/java/com/tickerBell/domain/member/controller/MemberApiControllerTest.java

로그인 성공, 사용자 아이디 실패, 비밀번호 실패 테스트 작성

로그인 관련 테스트코드 작성

---

src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java

MemberService의 반환값을 ResponseEntity에서 Dto로 변경한 로직입니다.

서비스 계층 반환값 변경

---

src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/dtos/LoginRequest.java
src/main/java/com/tickerBell/domain/member/dtos/LoginResponse.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/domain/member/service/OauthServiceImpl.java
src/test/java/com/tickerBell/domain/member/controller/MemberApiControllerTest.java

로그인 api 스웨거 설명 추가 및 dto 패키지 구조 변경

로그인 api 스웨거 추가

---

src/main/java/com/tickerBell/domain/category/entity/Category.java
src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/image/entity/Image.java
src/main/java/com/tickerBell/domain/tag/entity/Tag.java
src/main/java/com/tickerBell/domain/ticketing/entity/Ticketing.java

refactor: 오타 수정, 엔티티에 setter 제거

refactor: 오타 수정, 엔티티에 setter 제거

---

.github/workflows/deploy.yml

feat: githubaction test 없이 build

feat: githubaction test 없이 build

---

build.gradle

jacoco 설정 추가

---

src/main/java/com/tickerBell/global/exception/CustomException.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java

CustomException 생성자 변경 및, 토큰 재발급 성공, 로그인 성공/실패 테스트 작성

MemberService 테스트 추가

---

src/main/java/com/tickerBell/domain/event/entity/Event.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java

이벤트 엔티티 생성자 변경 및 이벤트 저장 테스트 작성

이벤트 저장 테스트 작성

---

src/main/java/com/tickerBell/domain/category/entity/Categories.java
src/main/java/com/tickerBell/domain/category/entity/Category.java
src/main/java/com/tickerBell/domain/category/service/CategoryService.java
src/main/java/com/tickerBell/domain/category/service/CategoryServiceImpl.java
src/main/java/com/tickerBell/domain/event/dtos/SaveEventRequest.java
src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/event/service/EventService.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/main/java/com/tickerBell/domain/member/entity/Role.java
src/main/java/com/tickerBell/global/exception/ErrorCode.java
src/main/java/com/tickerBell/global/security/config/SecurityConfig.java
src/main/java/com/tickerBell/global/security/filter/JwtFilter.java
src/test/java/com/tickerBell/domain/category/repository/CategoryRepositoryTest.java
src/test/java/com/tickerBell/domain/category/service/CategoryServiceTest.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/member/repository/MemberRepositoryTest.java

이벤트 및 카테고리 저장 repo, service, test 구현

이벤트 및 카테고리 저장 구현

---

src/main/java/com/tickerBell/domain/event/controller/EventApiController.java
src/main/java/com/tickerBell/domain/specialseat/entity/SpecialSeat.java
src/main/java/com/tickerBell/domain/specialseat/repository/SpecialSeatRepository.java
src/main/java/com/tickerBell/domain/specialseat/service/SpecialSeatService.java
src/main/java/com/tickerBell/domain/specialseat/service/SpecialSeatServiceImpl.java
src/main/java/com/tickerBell/domain/tag/entity/Tag.java
src/test/java/com/tickerBell/domain/event/controller/EventApiControllerTest.java
src/test/java/com/tickerBell/domain/specialseat/repository/SpecialSeatRepositoryTest.java
src/test/java/com/tickerBell/domain/specialseat/service/SpecialSeatServiceTest.java
src/test/java/com/tickerBell/domain/tag/repository/TagRepositoryTest.java
src/test/resources/application.yml

태그 기능을 제외하고 이벤트 등록 api 및 테스트 코드를 작성하였습니다.

태그 기능을 제외한 이벤트 등록 api 구현

---

src/main/java/com/tickerBell/domain/event/controller/EventApiController.java
src/main/java/com/tickerBell/domain/tag/service/TagService.java
src/main/java/com/tickerBell/domain/tag/service/TagServiceImpl.java
src/test/java/com/tickerBell/domain/tag/service/TagServiceTest.java

태그 저장 로직 구현

---

src/main/java/com/tickerBell/domain/event/controller/EventApiController.java
src/main/java/com/tickerBell/domain/event/service/EventService.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java

카테고리를 통한 이벤트 조회 로직 변경

---

src/main/java/com/tickerBell/domain/event/dtos/EventResponse.java
src/main/java/com/tickerBell/domain/event/repository/EventRepository.java
src/main/java/com/tickerBell/domain/event/service/EventService.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java

이벤트 상세 조회 서비스 및 리포지토리 계층 구현 및 테스트

이벤트 상세 조회 서비스 및 리포지토리 계층 구현

---

src/main/java/com/tickerBell/domain/event/controller/EventApiController.java
src/main/java/com/tickerBell/domain/event/dtos/EventResponse.java
src/main/java/com/tickerBell/domain/event/dtos/SaveEventRequest.java
src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/main/java/com/tickerBell/domain/member/entity/Member.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/global/InitDB.java
src/main/java/com/tickerBell/global/exception/CustomException.java
src/test/java/com/tickerBell/domain/event/controller/EventApiControllerTest.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/member/repository/MemberRepositoryTest.java

회의 안건 반영 및 PK를 통한 이벤트 조회 구현

---

src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/dtos/JoinMemberRequest.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/test/java/com/tickerBell/domain/event/controller/EventApiControllerTest.java
src/test/java/com/tickerBell/domain/member/controller/MemberApiControllerTest.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java

회원 이메일 관련 api 및 테스트 로직 삭제

---

src/main/java/com/tickerBell/domain/casting/entity/Casting.java
src/main/java/com/tickerBell/domain/casting/repository/CastingRepository.java
src/main/java/com/tickerBell/domain/event/dtos/EventResponse.java
src/main/java/com/tickerBell/domain/event/dtos/SaveEventRequest.java
src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/main/java/com/tickerBell/domain/host/entity/Host.java
src/main/java/com/tickerBell/domain/host/repository/HostRepository.java
src/test/java/com/tickerBell/domain/casting/repository/CastingRepositoryTest.java
src/test/java/com/tickerBell/domain/event/controller/EventApiControllerTest.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/host/repository/HostRepositoryTest.java

host, casting 테이블 분리 및 이벤트 등록 validation, 이벤트 구매 가능 시간 로직 개발

host, casting 테이블 분리

---

src/main/java/com/tickerBell/domain/casting/repository/CastingRepository.java
src/main/java/com/tickerBell/domain/event/controller/EventApiController.java
src/main/java/com/tickerBell/domain/event/dtos/SaveEventRequest.java
src/main/java/com/tickerBell/domain/host/repository/HostRepository.java
src/main/java/com/tickerBell/domain/image/service/ImageService.java
src/main/java/com/tickerBell/domain/image/service/ImageServiceImpl.java
src/main/java/com/tickerBell/global/exception/ErrorCode.java
src/test/java/com/tickerBell/domain/casting/repository/CastingRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/host/repository/HostRepositoryTest.java

이벤트 등록 시 이미지 관련 로직 추가

---

src/main/java/com/tickerBell/domain/event/dtos/EventResponse.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/main/java/com/tickerBell/domain/image/service/ImageService.java
src/main/java/com/tickerBell/domain/image/service/ImageServiceImpl.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/image/service/ImageServiceTest.java

이벤트 조회 로직 및 테스트 개발 

---

build.gradle
src/main/java/com/tickerBell/domain/casting/entity/Casting.java
src/main/java/com/tickerBell/domain/event/dtos/EventResponse.java
src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/event/repository/EventRepository.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/main/java/com/tickerBell/domain/host/entity/Host.java
src/main/java/com/tickerBell/domain/image/entity/Image.java
src/main/java/com/tickerBell/domain/tag/entity/Tag.java
src/test/java/com/tickerBell/domain/casting/repository/CastingRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/host/repository/HostRepositoryTest.java
src/test/java/com/tickerBell/domain/tag/repository/TagRepositoryTest.java
src/test/resources/application.yml

이벤트 엔티티 양방향 연관관계 설정

---

src/main/java/com/tickerBell/domain/casting/entity/Casting.java
src/main/java/com/tickerBell/domain/event/dtos/EventResponse.java
src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/event/repository/EventRepository.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/main/java/com/tickerBell/domain/host/entity/Host.java
src/main/java/com/tickerBell/domain/image/entity/Image.java
src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/dtos/MyPageResponse.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/domain/selectedSeat/entity/SelectedSeat.java
src/main/java/com/tickerBell/domain/tag/entity/Tag.java
src/main/java/com/tickerBell/domain/ticketing/entity/Ticketing.java
src/main/java/com/tickerBell/domain/ticketing/repository/TicketingRepository.java
src/test/java/com/tickerBell/domain/casting/repository/CastingRepositoryTest.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/host/repository/HostRepositoryTest.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java
src/test/java/com/tickerBell/domain/tag/repository/TagRepositoryTest.java
src/test/java/com/tickerBell/domain/ticketing/repository/TicketingRepositoryTest.java
src/test/java/com/tickerBell/domain/ticketing/service/TicketingServiceImplTest.java

마이페이지 서비스 로직 구현

---

src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/dtos/MemberResponse.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/global/security/config/SecurityConfig.java
src/test/java/com/tickerBell/domain/member/controller/MemberApiControllerTest.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java

회원 정보 조회 api 추가

---

src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/test/java/com/tickerBell/domain/event/controller/EventApiControllerTest.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/specialseat/service/SpecialSeatServiceTest.java

이벤트 엔티티 생성자 변경 및 테스트 수행

---

.github/workflows/deploy.yml

main 브랜치 pr 시 CI/CD 적용

---

src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/dtos/MyPageResponse.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/global/config/S3Config.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java
src/test/java/com/tickerBell/global/config/MockS3Config.java

MyPage 이벤트 취소여부 추가

---

build.gradle
src/main/java/com/tickerBell/domain/member/dtos/MemberResponse.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/global/config/S3Config.java
src/test/java/com/tickerBell/domain/member/controller/MemberApiControllerTest.java
src/test/java/com/tickerBell/global/config/MockRedisConfig.java
src/test/java/com/tickerBell/global/config/MockS3Config.java

마이페이지 조회 데이터 확대 해결

---

src/main/java/com/tickerBell/domain/event/controller/EventApiController.java
src/main/java/com/tickerBell/domain/event/repository/EventRepositoryCustom.java
src/main/java/com/tickerBell/domain/event/repository/EventRepositoryImpl.java
src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/dtos/MyPageResponse.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/main/java/com/tickerBell/domain/ticketing/repository/TicketingRepository.java
src/main/java/com/tickerBell/domain/ticketing/repository/TicketingRepositoryCustom.java
src/main/java/com/tickerBell/domain/ticketing/repository/TicketingRepositoryCustomImpl.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java
src/test/java/com/tickerBell/domain/ticketing/repository/TicketingRepositoryTest.java

마이페이지 조회 시 event 페이징처리

---

src/main/java/com/tickerBell/domain/alarm/domain/Alarm.java
src/main/java/com/tickerBell/domain/alarm/dtos/SaveAlarmRequest.java
src/main/java/com/tickerBell/domain/alarm/repository/AlarmRepository.java
src/main/java/com/tickerBell/domain/alarm/service/AlarmService.java
src/main/java/com/tickerBell/domain/alarm/service/AlarmServiceImpl.java
src/main/java/com/tickerBell/domain/emitter/controller/EmitterApiController.java
src/main/java/com/tickerBell/domain/emitter/repository/EmitterRepository.java
src/main/java/com/tickerBell/domain/emitter/repository/MemoryEmitterRepository.java
src/main/java/com/tickerBell/domain/emitter/service/EmitterService.java
src/main/java/com/tickerBell/domain/emitter/service/EmitterServiceImpl.java
src/main/java/com/tickerBell/domain/event/controller/EventApiController.java
src/main/java/com/tickerBell/domain/event/dtos/SaveEventRequest.java
src/main/java/com/tickerBell/domain/event/service/EventService.java
src/main/java/com/tickerBell/domain/event/service/EventServiceImpl.java
src/main/java/com/tickerBell/domain/image/controller/ImageController.java
src/main/java/com/tickerBell/domain/image/dtos/EventImageResponse.java
src/main/java/com/tickerBell/domain/image/entity/Image.java
src/main/java/com/tickerBell/domain/image/repository/ImageRepository.java
src/main/java/com/tickerBell/domain/image/service/ImageService.java
src/main/java/com/tickerBell/domain/image/service/ImageServiceImpl.java
src/main/java/com/tickerBell/global/exception/ErrorCode.java
src/main/java/com/tickerBell/global/security/config/SecurityConfig.java
src/test/java/com/tickerBell/domain/emitter/controller/EmitterApiControllerTest.java
src/test/java/com/tickerBell/domain/emitter/repository/EmitterRepositoryTest.java
src/test/java/com/tickerBell/domain/emitter/service/EmitterServiceTest.java
src/test/java/com/tickerBell/domain/event/controller/EventApiControllerTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java
src/test/java/com/tickerBell/domain/image/controller/ImageControllerTest.java
src/test/java/com/tickerBell/domain/image/service/ImageServiceTest.java

이벤트 등록 시 이미지 따로 처리

---

src/main/java/com/tickerBell/domain/event/dtos/SaveEventRequest.java
src/main/java/com/tickerBell/domain/event/entity/Event.java
src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/test/java/com/tickerBell/domain/event/controller/EventApiControllerTest.java
src/test/java/com/tickerBell/domain/event/repository/EventRepositoryTest.java
src/test/java/com/tickerBell/domain/event/service/EventServiceTest.java

이벤트 등록 시 하루 중 시작 시간 추가

---

src/main/java/com/tickerBell/domain/event/repository/EventRepository.java
src/main/java/com/tickerBell/domain/member/controller/MemberApiController.java
src/main/java/com/tickerBell/domain/member/service/MemberService.java
src/main/java/com/tickerBell/domain/member/service/MemberServiceImpl.java
src/test/java/com/tickerBell/domain/member/service/MemberServiceTest.java

마이페이지 조회 시 필터링 조건 추가
